# list of extensions that you want to give a human readable name
# all extensions may be used; the value in extension is what asterisk will actually call
extensions:
- name: "Jon Doe"
  extension: "702"

# list of contexts you want to be able to specify for call forwards
# contexts that are not defined here can NOT be used to call forward in
contexts:
- display_name: "Extern"
  asterisk_name: "from_external"
- display_name: "Internal"
  asterisk_name: "from_internal"

db_user: "asterconf"
db_password: "NOT_THE_PASSWORD"
db_port: 5432
db_host: "postgres.example.com"
db_database: "asterconf"

tls_cert_file: "TODO"
tls_key_file: "TODO"

web_bind_addr: "127.0.0.1"
web_bind_port: 8080
web_bind_port_tls: 8443

agi_bind_addr: "127.0.0.1"
agi_bind_port: 4573
agi_digest_secret: "NOT_THE_SECRET"

# config for LDAP.
# only LDAPS is supported. It is my strong opinion that non-TLS LDAP should NEVER EVER be used in any circumstance.
# Connection to Unix sockets is currently not supported either because I did not need it.
ldap:
  # will bind to: ldaps://{hostname}:{port}
  hostname: "ldaps.example.com"
  port: 636
  bind_user: "uid=asterconf_search,cn=users,dc=example,dc=com"
  bind_password: "NOT_THE_PASSWORD"
  base_dn: "dc=example,dc=com"
  # {username} will be expanded to the username supplied by the user when searching for a user
  user_filter: "&(memberOf=cn=group,dc=example,dc=com)(uid={username})"

