CREATE TABLE timeframe_monthly
( monthly_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
, start_dom SMALLINT NOT NULL
, start_time TIME NOT NULL
, end_dom SMALLINT NOT NULL
, end_time TIME NOT NULL
);


